version: "3.3"

services:
  oxyg3nium_gpu_miner:
    image: oxyg3nium/gpu-miner:latest
    depends_on:
      - oxyg3nium
    restart: unless-stopped
    runtime: nvidia
    privileged: true
    command:
      - -a
      - oxyg3nium
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
