version: "3.3"

volumes:
  prometheus_data: {}
  grafana_data: {}
  oxyg3nium-data: {}
  oxyg3nium-wallets: {}

services:
  oxyg3nium:
    image: oxyg3nium/oxyg3nium:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "150m"
        max-file: "30"
    ports:
      # 9973 (udp and tcp) is used for external p2p connection and must be exposed
      - 9973:9973/tcp
      - 9973:9973/udp
      # ws and http port might not be widely exposed, but to your internal clique/apps/network only.
      # Defaults are set to not open these two ports publicly. Configure this with caution.
      - 127.0.0.1:10973:10973
      - 127.0.0.1:11973:11973
      - 127.0.0.1:12973:12973
    security_opt:
      - no-new-privileges:true
    # Set volumes or mounts to avoid loosing data/wallets.
    # Hint: mounts must be chown'ed to nobody:
    # mkdir ./oxyg3nium-data ./oxyg3nium-wallets && chown nobody ./oxyg3nium-data ./oxyg3nium-wallets
    volumes:
      # The provided file user.conf is a minimal default config to connect your container to the mainnet.
      - oxyg3nium-data:/oxyg3nium-home/.oxyg3nium
      - oxyg3nium-wallets:/oxyg3nium-home/.oxyg3nium-wallets
      - ./user.conf:/oxyg3nium-home/.oxyg3nium/user.conf

  grafana:
    image: grafana/grafana:7.2.1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
